version: "3.8"

services:
  yuyuko1:
    image: hub.dns.360.cn/dns/yuyuko:latest
    command: python yuyuko.py
    volumes:
    - ./env:/etc/yuyuko/.env
  yuyuko2:
    image: hub.dns.360.cn/dns/yuyuko:latest
    command: python yuyuko.py
    volumes:
    - ./env:/etc/yuyuko/.env
  yuyuko3:
    image: hub.dns.360.cn/dns/yuyuko:latest
    command: python yuyuko.py
    volumes:
    - ./env:/etc/yuyuko/.env
  fe:
    image: hub.dns.360.cn/dns/yuyuko-fe:latest
    ports:
    - "443:80"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
